### ISSUE TITLE
repeat

### ISSUE THREAD

**Issue by olutosinATflatiron** [learn-co-curriculum/locationTrivia-objects#8]
"should have an empty string for their name property Have it pass in an empty string for name,"

**Comment by markedwardmurray** [comment]
Can you be more specific about the problem? Is this a redundant instruction? Which line is it on in the readme?

**Comment by AnnJohn** [comment]
@olutosinATflatiron  ^^

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue is being closed now as stale. If the issue is encountered again, please first consult the [Learn Help Center](http://help.learn.co/) and the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature. If neither of those options resolves the problem and you still feel that this is an issue with the curriculum, please reopen this issue and provide as much detail as possible:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 🙂
